test1: project.py
	python3 test_part1.py
	md5sum pic_original.bmp
	md5sum prj_ecb.bin
	md5sum prj_dec.bmp
	md5sum prj_ecb.bmp
	eog prj_ecb.bmp &

test2: project.py
	python3 test_part2.py
	md5sum prj_cbc.bin
	md5sum prj_cbc_dec.bmp
	md5sum prj_ctr.bin
	md5sum prj_ctr_dec.bmp
